/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/symbols/search/{symbol}': {
    /** Returns an array of symbol data. */
    get: operations['searchSymbols'];
  };
}

export interface definitions {
  SymbolData: {
    /** @description Symbol */
    symbol?: string;
    /** @description Company name */
    description?: string;
    /** @description Listed Market */
    'listed-market'?: string;
    /** @description Price Increments */
    'price-increments'?: string;
    /** @description Trading Hours */
    'trading-hours'?: string;
    /** @description Has listed options */
    options?: boolean;
    /** @description Instrument Type */
    'instrument-type'?: string;
  };
}

export interface operations {
  /** Returns an array of symbol data. */
  searchSymbols: {
    parameters: {
      path: {
        /** Symbol or fragment of a symbol to search, i.e. `AAP` will return AAP and AAPL data */
        symbol: string;
      };
    };
    responses: {
      /** Returns an array of symbol data. */
      200: {
        schema: definitions['SymbolData'];
      };
    };
  };
}

export interface external {}
